version: '3.8'

services:
  redpanda:
    image: redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false
    ports:
      - "9092:9092"
      - "9644:9644"
    environment:
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
